"""Table: comments - Add:isApproved

Revision ID: 04e1278e1a75
Revises: 510200232095
Create Date: 2025-06-01 18:39:45.632142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '04e1278e1a75'
down_revision: Union[str, None] = '510200232095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('isApproved', sa.Boolean(), nullable=False, comment='Indica si el comentario ha sido aprobado o no'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'isApproved')
    # ### end Alembic commands ###
