"""Revert of the last upgrade

Revision ID: 118c3003f82f
Revises: 8c0d3d8f6e38
Create Date: 2025-06-26 17:58:47.844316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '118c3003f82f'
down_revision: Union[str, None] = '8c0d3d8f6e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'userID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['userID'], ['id'], ondelete='CASCADE')
    op.alter_column('problems', 'authorID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('problems_ibfk_1', 'problems', type_='foreignkey')
    op.create_foreign_key(None, 'problems', 'users', ['authorID'], ['id'], ondelete='CASCADE')
    op.alter_column('reports', 'userID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('reports_ibfk_2', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['userID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_2', 'reports', 'users', ['userID'], ['id'], ondelete='SET NULL')
    op.alter_column('reports', 'userID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.create_foreign_key('problems_ibfk_1', 'problems', 'users', ['authorID'], ['id'], ondelete='SET NULL')
    op.alter_column('problems', 'authorID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 'users', ['userID'], ['id'], ondelete='SET NULL')
    op.alter_column('comments', 'userID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
