"""Campo skills en usuarios y title en notificaciones

Revision ID: 2f30827175d9
Revises: c42d3bef5f07
Create Date: 2025-04-22 17:09:30.020484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f30827175d9'
down_revision: Union[str, None] = 'c42d3bef5f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('notifications', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('notifications', 'content')
    op.add_column('users', sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skills')
    op.add_column('notifications', sa.Column('content', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('notifications', 'description')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
