"""Table: problems - Add:tags - Deleted: block

Revision ID: 510200232095
Revises: 2f30827175d9
Create Date: 2025-05-18 22:15:58.097048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '510200232095'
down_revision: Union[str, None] = '2f30827175d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'block')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('block', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
