"""Nuevas tablas y modificaciones en las existentes

Revision ID: 99410b32f82a
Revises: 9cf8e345f7df
Create Date: 2025-04-05 19:04:41.255876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '99410b32f82a'
down_revision: Union[str, None] = '9cf8e345f7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='El tipo de token puede ser verify o recovery'),
    sa.Column('isValid', sa.Boolean(), nullable=False, comment='Indica si el token es valido o no'),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('problems', sa.Column('hints', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('problems', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('profilePicture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('github', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), nullable=False, comment='Indica si el usuario ha verificado su cuenta.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isVerified')
    op.drop_column('users', 'github')
    op.drop_column('users', 'profilePicture')
    op.drop_column('users', 'bio')
    op.drop_column('problems', 'tags')
    op.drop_column('problems', 'hints')
    op.drop_table('tokens')
    # ### end Alembic commands ###
