"""Table: TestCase - Add:inputs,functionName,description

Revision ID: a98da53207c4
Revises: 04e1278e1a75
Create Date: 2025-06-16 17:31:47.494521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a98da53207c4'
down_revision: Union[str, None] = '04e1278e1a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('functionName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('test_cases', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('test_cases', sa.Column('inputs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('test_cases', 'input')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('input', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('test_cases', 'inputs')
    op.drop_column('test_cases', 'description')
    op.drop_column('test_cases', 'functionName')
    # ### end Alembic commands ###
