"""Campo de contraseñas convertida a strings

Revision ID: c42d3bef5f07
Revises: 99410b32f82a
Create Date: 2025-04-05 22:27:16.075085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c42d3bef5f07'
down_revision: Union[str, None] = '99410b32f82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               comment='La contraseña se guarda hasheada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BLOB(),
               nullable=True,
               comment=None,
               existing_comment='La contraseña se guarda hasheada')
    # ### end Alembic commands ###
