"""Table: Users - Deleted: profilePicture

Revision ID: d73705dd5140
Revises: cf03cfe99889
Create Date: 2025-06-23 11:53:43.488305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd73705dd5140'
down_revision: Union[str, None] = 'cf03cfe99889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePicture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePicture', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
