"""Table: TestCase - Add:inputs*json - Delete: functionName

Revision ID: ff787195a1be
Revises: a98da53207c4
Create Date: 2025-06-20 11:53:48.609776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff787195a1be'
down_revision: Union[str, None] = 'a98da53207c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('functionName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('problems', 'hints',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('submissions', 'timeUpdated')
    op.add_column('test_cases', sa.Column('inputs_json', sa.JSON(), nullable=True))
    op.add_column('test_cases', sa.Column('expected_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('test_cases', 'functionName')
    op.drop_column('test_cases', 'output')
    op.drop_column('test_cases', 'inputs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('inputs', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('test_cases', sa.Column('output', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('test_cases', sa.Column('functionName', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('test_cases', 'expected_output')
    op.drop_column('test_cases', 'inputs_json')
    op.add_column('submissions', sa.Column('timeUpdated', mysql.DATETIME(), nullable=True))
    op.alter_column('problems', 'hints',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('problems', 'functionName')
    # ### end Alembic commands ###
